# Generated by Django 4.0 on 2021-12-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pictures/')),
                ('ingredients', models.TextField()),
                ('times', models.TimeField()),
                ('guide', models.TextField()),
            ],
            options={
                'verbose_name': 'Recette',
                'ordering': ('title',),
            },
        ),
    ]
