# Generated by Django 3.2.9 on 2021-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0003_alter_receipe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category de recette',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
